[package]
name = "ame"
version = "0.5.1"
description = "AME — Gestion de stock BTP"
authors = ["Eddin Adou"]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "ame_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
